// <auto-generated />
namespace FileObmen.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Role : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Role));
        
        string IMigrationMetadata.Id
        {
            get { return "201604261833339_Role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
