// <auto-generated />
namespace FileObmen.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AvatarPath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AvatarPath));
        
        string IMigrationMetadata.Id
        {
            get { return "201605011802275_AvatarPath"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
