// <auto-generated />
namespace FileObmen.Migrations
{
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Migration1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migration1));
        
        string IMigrationMetadata.Id
        {
            get { return "201601261116245_Migration1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
